# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 294c60a819ec8eba61fcbcfabb4f2bb2d4ffafe4625460d73d629c5772b78dddedb621e1097babc9fff5100ca8a2018e68b200dc23c64543bfd12db8107e4a76

test:
  secret_key_base: aa921f8edcb4e465d865b6ef2f2a6d5d9ec702628199df23a0ffb1d9447108c373833763e62713fc054e21da86d839890bd0640ed8592c132b1f90ffb4dbb2f5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
